name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache yarn
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Cache ~/.elm
        uses: actions/cache@v2
        id: elm-cache
        with:
          path: ~/.elm
          key: elm-${{ hashFiles('**/elm.json') }}-v1

      - run: yarn install

      - name: Build package
        run: yarn elm make

      - name: elm-format
        run: yarn elm-format --validate src examples

      - run: yarn elm-review

      # - run: yarn elm-test
